# Generated by Django 4.2.7 on 2025-07-09 07:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymousfeedback',
            name='delete_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='anonymousfeedback',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anonymousfeedback',
            name='original_input',
            field=models.TextField(blank=True, null=True),
        ),
    ]
